<?php

namespace LamaDelRay\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\queryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAdverts($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('a')
		->leftJoin('a.image', 'i')->addSelect('i')
		->leftJoin('a.categories', 'c')->addSelect('c')
		->orderBy('a.date', 'DESC')->getQuery();
		$query->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);
		return new Paginator($query, true);
	}
}
