platform_home:
    path:	/{page}
    defaults:
        _controller :	LamaDelRayPlatformBundle:Advert:index
        page:			1
    requirements:
        page: \d*


platform_view:
    path:	/advert/{id}
    defaults:	{ _controller : LamaDelRayPlatformBundle:Advert:view }
    requirements:
        id: \d+

platform_add:
    path:	/add
    defaults:	{ _controller : LamaDelRayPlatformBundle:Advert:add }

platform_edit:
    path:	/edit/{id}
    defaults:	{ _controller : LamaDelRayPlatformBundle:Advert:edit }
    requirements:
        id: \d+

platform_delete:
    path:	/delete/{id}
    defaults:	{ _controller : LamaDelRayPlatformBundle:Advert:delete }
    requirements:
        id: \d+

platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults:
        _controller: LamaDelRayPlatformBundle:Advert:viewSlug
        format: html
    requirements:
        year:	\d{4}
        format: html|xml

hello_world:
    path:     /hello_world/
    defaults: { _controller: LamaDelRayPlatformBundle:Advert:index }
