services:
#    lama_del_ray_platform.example:
#        class: LamaDelRay\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    LamaDelRay_platform.doctrine.notificqtion:
        class: LamaDelRay\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    LamaDelRay_platform.antispam:
        class: LamaDelRay\PlatformBundle\Antispam\LamaDelRayAntispam
        arguments: [@mailer, %locale%, 50]

    platform.validator.antiflood:
        class: LamaDelRay\PlatformBundle\Validator\AntifloodValidator
        arguments: [@request_stack, @doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: platform_antiflood}

