services:
#    lama_del_ray_platform.example:
#        class: LamaDelRay\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    LamaDelRay_platform.doctrine.notificqtion:
        class: LamaDelRay\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    LamaDelRay_platform.antispam:
        class: LamaDelRay\PlatformBundle\Antispam\LamaDelRayAntispam
        arguments: [@mailer, %locale%, 50]

    platform.validator.antiflood:
        class: LamaDelRay\PlatformBundle\Validator\AntifloodValidator
        arguments: [@request_stack, @doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: platform_antiflood}

    platform.antispam:
        class:  LamaDelRay\PlatformBundle\Antispam\LamaDelRayAntispam
        arguments: [@mailer, 50]
        calls:
            - [setLocale, [ %locale% ] ]
        tags:
            - { name: twig.extension }

    platform.beta.html:
       class: LamaDelRay\PlatformBundle\Beta\BetaHTML

    platform.beta.listener:
       class: LamaDelRay\PlatformBundle\Beta\BetaListener
       arguments: [@platform.beta.html, "2016-10-20"]
       tags:
           - { name: kernel.event_listener, event: kernel.response, method: processBeta }
           - { name: kernel.event_listener, event: kernel.controller, method: ignoreBeta }

    platform.censorship_processor:
        class:      LamaDelRay\PlatformBundle\Bigbrother\CensorshipProcessor
        arguments:  [@mailer]

    platform.censorship_listener:
        class:      LamaDelRay\PlatformBundle\Bigbrother\CensorshipListener
        arguments:  [@platform.censorship_processor, [1, 2, 3]]
        tags:
            - { name: kernel.event_listener, event: platform.bigbrother.post_message, method: processMessage }

